param(
  [Parameter(Mandatory=$false)]
  [string]$Repo = "",
  [Parameter(Mandatory=$false)]
  [string]$CsvPath = "C:\Users\Ben\Desktop\society-sim\backlog\SIMULATION_ISSUES_IMPORT.csv"
)

$ErrorActionPreference = "Stop"

if (-not (Get-Command gh -ErrorAction SilentlyContinue)) {
  throw "GitHub CLI (gh) is not installed or not in PATH."
}

if (-not (Test-Path $CsvPath)) {
  throw "CSV backlog file not found: $CsvPath"
}

if ($Repo -ne "") {
  gh repo set-default $Repo | Out-Null
}

$rows = Import-Csv $CsvPath

$milestones = $rows | Select-Object -ExpandProperty Milestone -Unique
foreach ($m in $milestones) {
  if ([string]::IsNullOrWhiteSpace($m)) { continue }
  $existing = gh api "repos/{owner}/{repo}/milestones?state=all" --jq ".[] | select(.title == \"$m\") | .title"
  if (-not $existing) {
    gh api --method POST "repos/{owner}/{repo}/milestones" -f title="$m" | Out-Null
  }
}

$labelSet = @{}
foreach ($r in $rows) {
  foreach ($label in ($r.Labels -split ',')) {
    $trim = $label.Trim()
    if ($trim -ne "") { $labelSet[$trim] = $true }
  }
  if ($r.Priority) { $labelSet["priority:$($r.Priority)"] = $true }
}

$existingLabels = gh api "repos/{owner}/{repo}/labels?per_page=200" --jq ".[].name"
foreach ($name in $labelSet.Keys) {
  if ($existingLabels -notcontains $name) {
    gh label create $name --color "1f6feb" --description "autogenerated by simulation backlog import" 2>$null
  }
}

foreach ($r in $rows) {
  $title = $r.Title
  $desc = @"
$r.Body

Meta:
- Priority: $($r.Priority)
- Estimate: $($r.EstimateEW) EW
- Depends On: $($r.DependsOn)
- Milestone: $($r.Milestone)
"@

  $labelArgs = @()
  foreach ($label in ($r.Labels -split ',')) {
    $trim = $label.Trim()
    if ($trim -ne "") { $labelArgs += "--label"; $labelArgs += $trim }
  }
  if ($r.Priority) { $labelArgs += "--label"; $labelArgs += "priority:$($r.Priority)" }

  $milestoneArgs = @()
  if (-not [string]::IsNullOrWhiteSpace($r.Milestone)) {
    $milestoneArgs += "--milestone"
    $milestoneArgs += $r.Milestone
  }

  gh issue create --title $title --body $desc @labelArgs @milestoneArgs | Out-Null
}

Write-Output "Import complete. Created $($rows.Count) issues."
